### ISSUE TITLE
shift+scrolldown does not update clip region until mouse move on OSX Chrome

### ISSUE THREAD

**Issue by stephenrparsons** [viscenter/layered-viewer#33]

**Comment by johnwalker** [comment]
is this also specific to osx chrome?

**Comment by stephenrparsons** [comment]
Yes, this is not a problem on ubuntu chrome.

**Comment by csparker247** [comment]
If you don't have a Mac to test on, you're welcome to use the extra computer here in my office.

**Comment by csparker247** [comment]
The primary canvas has to be redrawn after every shift + scroll event. It's fine to not redraw it if you're making the clipping region larger because you're effectively removing pixels that have already been drawn into the canvas. However, if you're scaling the clipping region down, you're effectively adding pixels back into the canvas and those have to be redrawn.
